PCA

El método de Análisis de Componentes Principales nos ayuda a determinar las direcciones de mayor crecimiento o mayor evolución de un sistema de variables en un espacio de n dimensiones.
Para esto se requieren las variables a determinar su PCA.
 

In [7]:
import pandas as pd
import numpy as np

#Si queremos capturar los datos desde terminal
#Definimos una función 

h = input("Determina los encabezados separados por comas: ")
headers = h.split(',')    # Encabezados del dataframe
n = int(input("Determiname el numero de datos que tienen las variables: "))
    

def matriz(headers, n):
    data = pd.DataFrame(np.zeros((n,len(headers))), columns=headers[:])
    #Solicitar al usuario ingresar los datos para cada header
    for encabezado in headers[:]: data[encabezado] = [int(input(f"Ingrese el dato para {encabezado} en la fila {i + 1}: ")) for i in range(n)]
    
    return data

data = pd.DataFrame(matriz(headers,n))



   x1  x2  x3
0   1   4   7
1   2   5   8
2   3   6   9


In [19]:
print(data)

   x1  x2  x3
0   1   4   7
1   2   5   8
2   3   6   9


Tenemos dos metodos para calcular el PCA.

1.- Método basado en la matriz de correlación, cuando los datos no son dimensionalmente homogéneos o el orden de magnitud de las variables aleatorias medidas no es el mismo.

2.- Método basado en la matriz de covarianzas, que se usa cuando los datos son dimensionalmente homogenéos y presentan valores medios similares.

La diferencia entre la matriz de correlación y la matriz de covarianzas es que la matriz de correlación esta normalizada y define la fuerza de correlación entre variables dado un intervalo entre [1,-1] donde 1 representa una perfecta correlación (relacion directamente proporcional), -1 una perfecta correlación negativa (relacion inversamente proporcional). Valores cercanos a 0 implican una correlación débil.



In [22]:
#Calculamos los vectores centrados:
med = np.zeros(len(headers))
datos_centrados = pd.DataFrame(np.zeros((n,len(headers))))
med = data.mean(axis = 0)
for i in range(0,len(headers),1): 
    datos_centrados.iloc[:,i] = data.iloc[:,i]-med[i] 
print(f"las medias son: {med} y la matriz centralizada es: {datos_centrados}")



las medias son: x1    2.0
x2    5.0
x3    8.0
dtype: float64 y la matriz centralizada es:      0    1    2
0 -1.0 -1.0 -1.0
1  0.0  0.0  0.0
2  1.0  1.0  1.0


Se calculo los factores $(x_{i}^{1}-E[x^{1}])$, $(x_{i}^{2}-E[x^{2}])$ y $(x_{i}^{3}-E[x^{3}])$ donde los supraindices denotan las correspondientes variables y los subinidices los datos correspondientes a la variable $x^{n}$
La matriz de covarianza esta dada por:


$cov(x,y) = E[(x-E[x])(y-E[y])]$

a partir de los factores calculamos la matriz.

In [18]:
matriz_covarianza = pd.DataFrame([datos_centrados.iloc[:,j]*datos_centrados.iloc[j,:] for j in range(0,n,1)])

print(matriz_covarianza)



     0    1    2
0  1.0 -0.0 -1.0
1 -0.0  0.0  0.0
2 -1.0  0.0  1.0


La libreria Numpy maneja una función para calcular la matriz de covarianza a partir de un conjunto de datos, tenemos los siguientes argumentos:

**np.cov(data, y = None, rovwar = True, bias = False. ddof = None, fweights = None, aweights = None, * , dtype = None)**

|**data** : array unidimensional o bidimensional, cada fila de **data** representa una variable y cada columna una sola opservacion de esas variables.

|**y** : un set adicional de variables y observaciones, **y** tiene que tener la misma dimension o forma que **data**

|**rowvar** : si **rowvar** es *True* (default) , entonces cada fila representa una variable, con las observaciones en las columnas, en dado caso de que esten transpuestos los datos con respecto a esta referencia, seria *False*

|**bias** : *normalización* por default (*False*) es **(N-1)**, donde N es el numero de observaciones dadas (estimación no sesgada), Sí **bias** es *True*, entonces la normalizacion es por *N*, esos valores pueden ser anulados.

In [17]:
mcov = np.cov(data, bias = True)
print(mcov)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
